project:
  type: website

website:
  title: "罗秋艳 | 个人主页"
  navbar:
    left:
      - text: "首页"
        href: index.qmd
      - text: "教育背景"
        href: education.qmd
      - text: "关于我"
        href: about.qmd
    background: "#2c3e50"
    foreground: "#ffffff"
    search: true
    pinned: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full